### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by wenfangdu** [3nuc/demo-vue-eslint-force-dot-vue-extension-in-imports#1]
I changed this line
![image](https://user-images.githubusercontent.com/28700378/87246840-5e977c00-c482-11ea-88ea-49ea2eb38a4f.png)
But doesn't take effect for js files
![image](https://user-images.githubusercontent.com/28700378/87246850-69eaa780-c482-11ea-973f-9832e190759d.png)
If I change `always`  to `ignorePackages`
![image](https://user-images.githubusercontent.com/28700378/87246896-cf3e9880-c482-11ea-9f92-385bdfc424aa.png)
Doesn't work for vue files either
![image](https://user-images.githubusercontent.com/28700378/87246889-c0f07c80-c482-11ea-88dd-440d90cc35c7.png)

UPDATE
This is so weird, after I changed the path one level deeper, the error shows up
![image](https://user-images.githubusercontent.com/28700378/87247305-a7046900-c485-11ea-9049-9785c827b5ea.png)

**Comment by 3nuc** [comment]
Hm, here's my suspicion:
You know package names like `@vue/cli`? I think it's treating `@/miscfile` the same way as `@vue/cli` and assuming it's a package.

https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/importType.js#L95
I think this is the code responsible for the error we're seeing. It should read like "if first letter is @ AND it's not @/"

**Comment by 3nuc** [comment]
Possible upstream issue in https://github.com/benmosher/eslint-plugin-import/issues/1851

**Comment by 3nuc** [comment]
@wenfangdu My fix is merged. Need to wait for release of eslint-plugin-import 2.23 in ~2 weeks?

**Comment by wenfangdu** [comment]
👍

**Comment by 3nuc** [comment]
The fix for this was released in https://github.com/benmosher/eslint-plugin-import/releases/tag/v2.22.1

I updated the repo.

To anyone who has the same issue in the future: please run:
* `npm list eslint-plugin-import` and make sure the version of eslint-plugin-import is >= 2.22.1

**Comment by wenfangdu** [comment]
Sorry, two issues still persist, please check out [my fork](https://github.com/wenfangdu/demo-vue-eslint-force-dot-vue-extension-in-imports)
![image](https://user-images.githubusercontent.com/28700378/94563988-02324480-029a-11eb-9612-87b25859a0a8.png)
![image](https://user-images.githubusercontent.com/28700378/94564030-11b18d80-029a-11eb-81fa-78d342e051a6.png)

**Comment by wenfangdu** [comment]
I've submitted a PR(https://github.com/benmosher/eslint-plugin-import/pull/1925) regarding this

**Comment by wenfangdu** [comment]
Closing this as https://github.com/benmosher/eslint-plugin-import/issues/1914 is closed
